/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChimeButtonGroup {
        /**
          * @prop boxes: Control the number of buttons within the group. Using an odd number is highly recommended.
          * @default 5
         */
        "boxes": number;
        /**
          * @prop highLabel: An optional label that will be placed near  the upper button.
         */
        "highLabel": string;
        /**
          * @prop lowLabel: An optional label that will be placed near  the lower button.
         */
        "lowLabel": string;
        /**
          * @prop midLabel: An optional label that will be placed near the middle button. Only works for odd numbers of buttons.
         */
        "midLabel": string;
    }
    interface ChimeGmailTooltip {
        /**
          * @prop companyImage - path to the company's logo
         */
        "companyImage": string | null;
        /**
          * @prop position - object that takes a top and right value that will position the tooltip based on the tip being (0, 0)
         */
        "position": {top: string, right: string};
        /**
          * @prop questionOriginator - entity who asked the question
         */
        "questionOriginator": string | null;
    }
}
declare global {
    interface HTMLChimeButtonGroupElement extends Components.ChimeButtonGroup, HTMLStencilElement {
    }
    var HTMLChimeButtonGroupElement: {
        prototype: HTMLChimeButtonGroupElement;
        new (): HTMLChimeButtonGroupElement;
    };
    interface HTMLChimeGmailTooltipElement extends Components.ChimeGmailTooltip, HTMLStencilElement {
    }
    var HTMLChimeGmailTooltipElement: {
        prototype: HTMLChimeGmailTooltipElement;
        new (): HTMLChimeGmailTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "chime-button-group": HTMLChimeButtonGroupElement;
        "chime-gmail-tooltip": HTMLChimeGmailTooltipElement;
    }
}
declare namespace LocalJSX {
    interface ChimeButtonGroup {
        /**
          * @prop boxes: Control the number of buttons within the group. Using an odd number is highly recommended.
          * @default 5
         */
        "boxes"?: number;
        /**
          * @prop highLabel: An optional label that will be placed near  the upper button.
         */
        "highLabel"?: string;
        /**
          * @prop lowLabel: An optional label that will be placed near  the lower button.
         */
        "lowLabel"?: string;
        /**
          * @prop midLabel: An optional label that will be placed near the middle button. Only works for odd numbers of buttons.
         */
        "midLabel"?: string;
    }
    interface ChimeGmailTooltip {
        /**
          * @prop companyImage - path to the company's logo
         */
        "companyImage"?: string | null;
        /**
          * @prop position - object that takes a top and right value that will position the tooltip based on the tip being (0, 0)
         */
        "position"?: {top: string, right: string};
        /**
          * @prop questionOriginator - entity who asked the question
         */
        "questionOriginator"?: string | null;
    }
    interface IntrinsicElements {
        "chime-button-group": ChimeButtonGroup;
        "chime-gmail-tooltip": ChimeGmailTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "chime-button-group": LocalJSX.ChimeButtonGroup & JSXBase.HTMLAttributes<HTMLChimeButtonGroupElement>;
            "chime-gmail-tooltip": LocalJSX.ChimeGmailTooltip & JSXBase.HTMLAttributes<HTMLChimeGmailTooltipElement>;
        }
    }
}
